version: "2"
services:
#  api:
#     build: .
#     ports:
#     - "3000:3000"
#     depends_on:
#     - mongodb
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume: